// Purchase summary export: Markdown + HTML + download helper. Print-to-PDF via window.print().
import { trueUnitCost, orderTotal } from "../data/quotes.js";

const inr = (n) => "Rs " + n.toLocaleString("en-IN");

function summaryLines(scn, choiceId) {
  const b = scn.business;
  const qty = b.quantity;
  const q = scn.quotes.find((x) => x.id === choiceId);
  const e = q.extracted;
  return { b, qty, q, e, t: trueUnitCost(q, qty), total: orderTotal(q, qty) };
}

export function buildMarkdown(scn, pipeline, choiceId) {
  const { b, qty, q, e, t, total } = summaryLines(scn, choiceId);
  const L = [];
  L.push(`# QuoteLens Purchase Summary — ${scn.id}`, `_${scn.title}_`, "");
  L.push(`> 100% synthetic demo data. No real businesses, people, or money.`, "");
  L.push(`## Buyer`, `${b.name}, ${b.location}`, `Need: ${b.need} (qty ${qty})`, "");
  L.push(`## Comparison (true per-unit cost)`);
  L.push(`| Supplier | Headline | True /unit | Order total |`);
  L.push(`|---|---|---|---|`);
  for (const x of scn.quotes)
    L.push(`| ${x.supplier} | ${inr(x.extracted.unitPrice)} | ${inr(trueUnitCost(x, qty))} | ${inr(orderTotal(x, qty))} |`);
  L.push("", `## Approved supplier`, `**${q.supplier}** — ${inr(t)}/unit, order total **${inr(total)}**`,
    `GST ${e.gst} · ${e.deliveryDays}-day delivery · ${e.warrantyMonths ?? "—"}-month warranty · ${e.advancePct}% advance · valid ${e.validDays} days`, "");
  if (pipeline) {
    L.push(`## Agent run (${pipeline.provider} provider)`);
    for (const [id, r] of Object.entries(pipeline.results))
      L.push(`- ${id}: ${r.summary} (${r.durationMs}ms, confidence ${r.confidence})`);
    L.push("");
  }
  L.push(`## Human approval`, `Approved by the buyer. The agent recommends — it never spends money.`, "");
  L.push(`---`, `_Generated by QuoteLens · ${new Date().toISOString()}_`);
  return L.join("\n");
}

export function buildHTML(scn, pipeline, choiceId) {
  const esc = (s) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;");
  const md = buildMarkdown(scn, pipeline, choiceId)
    .split("\n")
    .map((line) => {
      if (line.startsWith("# ")) return `<h1>${esc(line.slice(2))}</h1>`;
      if (line.startsWith("## ")) return `<h2>${esc(line.slice(3))}</h2>`;
      if (line.startsWith("|")) {
        const cells = line.split("|").filter((c) => c.trim() && c.trim() !== "---");
        if (/^[\s|\-:]+$/.test(line)) return "";
        return `<tr>${cells.map((c) => `<td>${esc(c.trim())}</td>`).join("")}</tr>`;
      }
      if (line.startsWith("> ")) return `<blockquote>${esc(line.slice(2))}</blockquote>`;
      if (line === "---") return "<hr>";
      if (!line.trim()) return "";
      return `<p>${esc(line)}</p>`;
    })
    .join("\n")
    .replace(/<tr>/g, (m, o, s) => s.slice(0, o).endsWith("</h2>\n<tr><td>Supplier") ? "<table><tr>" : m);
  return `<!doctype html><html><head><meta charset="utf-8"><title>QuoteLens Summary — ${esc(scn.id)}</title>` +
    `<style>body{font-family:system-ui,sans-serif;max-width:760px;margin:2rem auto;padding:0 1rem;color:#111}h2{margin-top:2rem;color:#1e40af}blockquote{background:#fef3c7;padding:.75rem;border-left:4px solid #f59e0b}table{border-collapse:collapse;width:100%}td{border:1px solid #ddd;padding:.4rem .6rem;font-size:.9rem}</style>` +
    `</head><body>${md}</body></html>`;
}

export function download(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    URL.revokeObjectURL(a.href);
    a.remove();
  }, 500);
}
